### ISSUE TITLE
Listener address/port

### ISSUE THREAD

**Issue by Lilja-at-funnel** [rawhat/grammy#1]
I tried to run the example grammy server from the documentation. But how do I know what host/port the server is listening to? I'm trying to read the code but there's no obvious answer(at least to me)

**Comment by Lilja-at-funnel** [comment]
Found it, it's 4000.

**Comment by rawhat** [comment]
I should definitely log that out though, so thanks for raising it!

**Comment by rawhat** [comment]
This is now printed when you start the server.  Thank you!

The address is currently not customizable.  I'd like to add that, but for now it's just `localhost`.
